# Generated by Django 4.2.14 on 2024-08-05 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="services",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service_img", models.CharField(max_length=60)),
                ("service_info", models.CharField(max_length=80)),
            ],
        ),
    ]
