# Generated by Django 4.2.16 on 2024-09-16 03:52

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0004_cone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cone",
            name="Cone_Des",
            field=tinymce.models.HTMLField(),
        ),
    ]
